plugins { id 'com.android.application' }

android {
    namespace 'com.chitnyihtwe.aivoicestudio'
    compileSdk 35

    defaultConfig {
        applicationId 'com.chitnyihtwe.aivoicestudio'
        minSdk 23
        targetSdk 35
        versionCode 3
        versionName '1.2'
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation files('libs/sherpa-onnx.aar')
    implementation platform('org.jetbrains.kotlin:kotlin-bom:1.8.22')
}

configurations.configureEach {
    resolutionStrategy {
        force 'org.jetbrains.kotlin:kotlin-stdlib:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.22'
    }
}
