plugins { id 'com.android.application' }

android {
    namespace 'com.chitnyihtwe.aivoicestudio'
    compileSdk 35

    defaultConfig {
        applicationId 'com.chitnyihtwe.aivoicestudio'
        minSdk 23
        targetSdk 35
        versionCode 3
        versionName '1.2'
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation files('libs/sherpa-onnx.aar')
}
